#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerPlaywright.TestApp.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum pp_record_pp_choice
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChoiceA = 125600000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChoiceB = 125600001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChoiceC = 125600002,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum pp_record_pp_choices
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChoiceA = 125600000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChoiceB = 125600001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChoiceC = 125600002,
	}
	
	/// <summary>
	/// Status of the Record
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum pp_record_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Record
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum pp_record_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Cancelled = 125600001,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("pp_record")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class pp_Record : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public pp_Record() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "pp_record";
		
		public const string EntityLogicalCollectionName = "pp_records";
		
		public const string EntitySetName = "pp_records";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the entity with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_choice")]
		public virtual pp_record_pp_choice? pp_choice
		{
			get
			{
				return ((pp_record_pp_choice?)(EntityOptionSetEnum.GetEnum(this, "pp_choice")));
			}
			set
			{
				this.OnPropertyChanging("pp_choice");
				this.SetAttributeValue("pp_choice", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("pp_choice");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_choices")]
		public virtual System.Collections.Generic.IEnumerable<pp_record_pp_choices> pp_choices
		{
			get
			{
				return EntityOptionSetEnum.GetMultiEnum<pp_record_pp_choices>(this, "pp_choices");
			}
			set
			{
				this.OnPropertyChanging("pp_choices");
				this.SetAttributeValue("pp_choices", EntityOptionSetEnum.GetMultiEnum(this, "pp_choices", value));
				this.OnPropertyChanged("pp_choices");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_currency")]
		public Microsoft.Xrm.Sdk.Money pp_currency
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("pp_currency");
			}
			set
			{
				this.OnPropertyChanging("pp_currency");
				this.SetAttributeValue("pp_currency", value);
				this.OnPropertyChanged("pp_currency");
			}
		}
		
		/// <summary>
		/// Value of the Currency in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_currency_base")]
		public Microsoft.Xrm.Sdk.Money pp_currency_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("pp_currency_base");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_dateandtimedateandtime")]
		public System.Nullable<System.DateTime> pp_dateandtimedateandtime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("pp_dateandtimedateandtime");
			}
			set
			{
				this.OnPropertyChanging("pp_dateandtimedateandtime");
				this.SetAttributeValue("pp_dateandtimedateandtime", value);
				this.OnPropertyChanged("pp_dateandtimedateandtime");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_dateandtimedateonly")]
		public System.Nullable<System.DateTime> pp_dateandtimedateonly
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("pp_dateandtimedateonly");
			}
			set
			{
				this.OnPropertyChanging("pp_dateandtimedateonly");
				this.SetAttributeValue("pp_dateandtimedateonly", value);
				this.OnPropertyChanged("pp_dateandtimedateonly");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_decimal")]
		public System.Nullable<decimal> pp_decimal
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("pp_decimal");
			}
			set
			{
				this.OnPropertyChanging("pp_decimal");
				this.SetAttributeValue("pp_decimal", value);
				this.OnPropertyChanged("pp_decimal");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_file")]
		public System.Nullable<System.Guid> pp_file
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("pp_file");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_float")]
		public System.Nullable<double> pp_float
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("pp_float");
			}
			set
			{
				this.OnPropertyChanging("pp_float");
				this.SetAttributeValue("pp_float", value);
				this.OnPropertyChanged("pp_float");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_image")]
		public byte[] pp_image
		{
			get
			{
				return this.GetAttributeValue<byte[]>("pp_image");
			}
			set
			{
				this.OnPropertyChanging("pp_image");
				this.SetAttributeValue("pp_image", value);
				this.OnPropertyChanged("pp_image");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_image_timestamp")]
		public System.Nullable<long> pp_image_Timestamp
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("pp_image_timestamp");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_image_url")]
		public string pp_image_URL
		{
			get
			{
				return this.GetAttributeValue<string>("pp_image_url");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_imageid")]
		public System.Nullable<System.Guid> pp_imageId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("pp_imageid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_multiplelinesoftexttext")]
		public string pp_multiplelinesoftexttext
		{
			get
			{
				return this.GetAttributeValue<string>("pp_multiplelinesoftexttext");
			}
			set
			{
				this.OnPropertyChanging("pp_multiplelinesoftexttext");
				this.SetAttributeValue("pp_multiplelinesoftexttext", value);
				this.OnPropertyChanged("pp_multiplelinesoftexttext");
			}
		}
		
		/// <summary>
		/// A self-referential lookup
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_parentrecord")]
		public Microsoft.Xrm.Sdk.EntityReference pp_ParentRecord
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("pp_parentrecord");
			}
			set
			{
				this.OnPropertyChanging("pp_ParentRecord");
				this.SetAttributeValue("pp_parentrecord", value);
				this.OnPropertyChanged("pp_ParentRecord");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_recordid")]
		public System.Nullable<System.Guid> pp_RecordId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("pp_recordid");
			}
			set
			{
				this.OnPropertyChanging("pp_RecordId");
				this.SetAttributeValue("pp_recordid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("pp_RecordId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_recordid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.pp_RecordId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_relatedrecord")]
		public Microsoft.Xrm.Sdk.EntityReference pp_relatedrecord
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("pp_relatedrecord");
			}
			set
			{
				this.OnPropertyChanging("pp_relatedrecord");
				this.SetAttributeValue("pp_relatedrecord", value);
				this.OnPropertyChanged("pp_relatedrecord");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_singlelineoftextemail")]
		public string pp_singlelineoftextemail
		{
			get
			{
				return this.GetAttributeValue<string>("pp_singlelineoftextemail");
			}
			set
			{
				this.OnPropertyChanging("pp_singlelineoftextemail");
				this.SetAttributeValue("pp_singlelineoftextemail", value);
				this.OnPropertyChanged("pp_singlelineoftextemail");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_singlelineoftextphonenumber")]
		public string pp_singlelineoftextphonenumber
		{
			get
			{
				return this.GetAttributeValue<string>("pp_singlelineoftextphonenumber");
			}
			set
			{
				this.OnPropertyChanging("pp_singlelineoftextphonenumber");
				this.SetAttributeValue("pp_singlelineoftextphonenumber", value);
				this.OnPropertyChanged("pp_singlelineoftextphonenumber");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_singlelineoftexttext")]
		public string pp_singlelineoftexttext
		{
			get
			{
				return this.GetAttributeValue<string>("pp_singlelineoftexttext");
			}
			set
			{
				this.OnPropertyChanging("pp_singlelineoftexttext");
				this.SetAttributeValue("pp_singlelineoftexttext", value);
				this.OnPropertyChanged("pp_singlelineoftexttext");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_singlelineoftexttextarea")]
		public string pp_singlelineoftexttextarea
		{
			get
			{
				return this.GetAttributeValue<string>("pp_singlelineoftexttextarea");
			}
			set
			{
				this.OnPropertyChanging("pp_singlelineoftexttextarea");
				this.SetAttributeValue("pp_singlelineoftexttextarea", value);
				this.OnPropertyChanged("pp_singlelineoftexttextarea");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_singlelineoftexttickersymbol")]
		public string pp_singlelineoftexttickersymbol
		{
			get
			{
				return this.GetAttributeValue<string>("pp_singlelineoftexttickersymbol");
			}
			set
			{
				this.OnPropertyChanging("pp_singlelineoftexttickersymbol");
				this.SetAttributeValue("pp_singlelineoftexttickersymbol", value);
				this.OnPropertyChanged("pp_singlelineoftexttickersymbol");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_singlelineoftexturl")]
		public string pp_singlelineoftexturl
		{
			get
			{
				return this.GetAttributeValue<string>("pp_singlelineoftexturl");
			}
			set
			{
				this.OnPropertyChanging("pp_singlelineoftexturl");
				this.SetAttributeValue("pp_singlelineoftexturl", value);
				this.OnPropertyChanged("pp_singlelineoftexturl");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_wholenumberduration")]
		public System.Nullable<int> pp_wholenumberduration
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("pp_wholenumberduration");
			}
			set
			{
				this.OnPropertyChanging("pp_wholenumberduration");
				this.SetAttributeValue("pp_wholenumberduration", value);
				this.OnPropertyChanged("pp_wholenumberduration");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_wholenumberlanguagecode")]
		public System.Nullable<int> pp_wholenumberlanguagecode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("pp_wholenumberlanguagecode");
			}
			set
			{
				this.OnPropertyChanging("pp_wholenumberlanguagecode");
				this.SetAttributeValue("pp_wholenumberlanguagecode", value);
				this.OnPropertyChanged("pp_wholenumberlanguagecode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_wholenumbernone")]
		public System.Nullable<int> pp_wholenumbernone
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("pp_wholenumbernone");
			}
			set
			{
				this.OnPropertyChanging("pp_wholenumbernone");
				this.SetAttributeValue("pp_wholenumbernone", value);
				this.OnPropertyChanged("pp_wholenumbernone");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_wholenumbertimezone")]
		public System.Nullable<int> pp_wholenumbertimezone
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("pp_wholenumbertimezone");
			}
			set
			{
				this.OnPropertyChanging("pp_wholenumbertimezone");
				this.SetAttributeValue("pp_wholenumbertimezone", value);
				this.OnPropertyChanged("pp_wholenumbertimezone");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_yesno")]
		public System.Nullable<bool> pp_yesno
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("pp_yesno");
			}
			set
			{
				this.OnPropertyChanging("pp_yesno");
				this.SetAttributeValue("pp_yesno", value);
				this.OnPropertyChanged("pp_yesno");
			}
		}
		
		/// <summary>
		/// Status of the Record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual pp_record_statecode? statecode
		{
			get
			{
				return ((pp_record_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual pp_record_statuscode? statuscode
		{
			get
			{
				return ((pp_record_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the currency associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N pp_record_ParentRecord_pp_record
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("pp_record_ParentRecord_pp_record", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<PowerPlaywright.TestApp.Model.pp_Record> Referencedpp_record_ParentRecord_pp_record
		{
			get
			{
				return this.GetRelatedEntities<PowerPlaywright.TestApp.Model.pp_Record>("pp_record_ParentRecord_pp_record", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			set
			{
				this.OnPropertyChanging("Referencedpp_record_ParentRecord_pp_record");
				this.SetRelatedEntities<PowerPlaywright.TestApp.Model.pp_Record>("pp_record_ParentRecord_pp_record", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
				this.OnPropertyChanged("Referencedpp_record_ParentRecord_pp_record");
			}
		}
		
		/// <summary>
		/// 1:N pp_Record_RelatedRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("pp_Record_RelatedRecord")]
		public System.Collections.Generic.IEnumerable<PowerPlaywright.TestApp.Model.pp_RelatedRecord> pp_Record_RelatedRecord
		{
			get
			{
				return this.GetRelatedEntities<PowerPlaywright.TestApp.Model.pp_RelatedRecord>("pp_Record_RelatedRecord", null);
			}
			set
			{
				this.OnPropertyChanging("pp_Record_RelatedRecord");
				this.SetRelatedEntities<PowerPlaywright.TestApp.Model.pp_RelatedRecord>("pp_Record_RelatedRecord", null, value);
				this.OnPropertyChanged("pp_Record_RelatedRecord");
			}
		}
		
		/// <summary>
		/// N:1 pp_record_ParentRecord_pp_record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_parentrecord")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("pp_record_ParentRecord_pp_record", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public PowerPlaywright.TestApp.Model.pp_Record Referencingpp_record_ParentRecord_pp_record
		{
			get
			{
				return this.GetRelatedEntity<PowerPlaywright.TestApp.Model.pp_Record>("pp_record_ParentRecord_pp_record", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
			set
			{
				this.OnPropertyChanging("Referencingpp_record_ParentRecord_pp_record");
				this.SetRelatedEntity<PowerPlaywright.TestApp.Model.pp_Record>("pp_record_ParentRecord_pp_record", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
				this.OnPropertyChanged("Referencingpp_record_ParentRecord_pp_record");
			}
		}
		
		/// <summary>
		/// N:1 pp_relatedrecord_record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pp_relatedrecord")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("pp_relatedrecord_record")]
		public PowerPlaywright.TestApp.Model.pp_RelatedRecord pp_relatedrecord_record
		{
			get
			{
				return this.GetRelatedEntity<PowerPlaywright.TestApp.Model.pp_RelatedRecord>("pp_relatedrecord_record", null);
			}
			set
			{
				this.OnPropertyChanging("pp_relatedrecord_record");
				this.SetRelatedEntity<PowerPlaywright.TestApp.Model.pp_RelatedRecord>("pp_relatedrecord_record", null, value);
				this.OnPropertyChanged("pp_relatedrecord_record");
			}
		}
	}
}
#pragma warning restore CS1591
