name: Power Playwright

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Run unit tests
        id: test
        run: dotnet test tests/PowerPlaywright.UnitTests/PowerPlaywright.UnitTests.csproj -c Release --logger console --logger html --no-build --results-directory TestResults
      - name: Upload unit test results
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: TestResults
        if: ${{ always() }}
      - name: Pack
        run: dotnet pack --no-restore --output nupkg
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: nupkg
      - name: Upload integration tests
        uses: actions/upload-artifact@v4
        with:
          name: integration-tests
          path: tests/PowerPlaywright.IntegrationTests/bin/Release/net8.0
          include-hidden-files: true
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Download integration tests
        uses: actions/download-artifact@v4
        with:
          name: integration-tests
          path: integration-tests
      - name: Setup Playwright
        run: |
          chmod +x integration-tests/.playwright/node/linux-x64/node
          integration-tests/playwright.ps1 install chromium --with-deps
        shell: pwsh
      - name: Run integration tests
        id: runTests
        run: dotnet test integration-tests/PowerPlaywright.IntegrationTests.dll --logger console --logger html --results-directory TestResults -- NUnit.NumberOfTestWorkers=2 Playwright.LaunchOptions.Headless=true
        env:
          KEYVAULT__URL: ${{ secrets.TEST_KEYVAULT_URL}}
          KEYVAULT__TENANTID: ${{ secrets.TEST_KEYVAULT_TENANTID}}
          KEYVAULT__CLIENTID: ${{ secrets.TEST_KEYVAULT_CLIENTID}} 
          KEYVAULT__CLIENTSECRET: ${{ secrets.TEST_KEYVAULT_CLIENTSECRET}} 
      - name: Upload integration test packages feed (temporary)
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-packages
          path: integration-tests/packages
        if: ${{ always() }}
      - name: Upload integration test results
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: TestResults
        if: ${{ always() }}
      - name: Login to Azure
        id: azureLogin
        if: ${{ failure() && steps.runTests.outcome == 'failure' }}
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
      - name: Upload traces to Blob Storage
        if: ${{ failure() && steps.azureLogin.conclusion == 'success' }}
        uses: azure/CLI@v2
        with:
          inlineScript: az storage blob upload-batch --account-name '${{ secrets.AZURE_STORAGE_ACCOUNTNAME }}' --auth-mode key -d 'playwright-traces' -s 'playwright-traces' --destination-path '${{ github.workflow }}/${{ github.run_id }}_${{ github.run_attempt }}' 
      - name: Logout of Azure
        if: ${{ failure() && steps.azureLogin.conclusion == 'success' }}
        run: az logout